language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
# command to install dependencies
# install: "pip install -r example_project/requirements.txt"
install:
  - "pip install tox tox-pyenv tox-travis"
# command to run tests
# script: python example_project/manage.py test fooapp
script:
  - tox
